#if !defined(USING_MAP_DATUM)

	#include "../../mods/content/actors.dm"
	#include "../../mods/content/mundane.dm"
	#include "../../mods/content/scaling_descriptors.dm"

	#include "../../mods/content/augments/_augments.dme"
	#include "../../mods/content/beekeeping/_beekeeping.dme"
//	#include "../../mods/content/bigpharma/_bigpharma.dme"
	#include "../../mods/content/biomods/_biomods.dme"
	#include "../../mods/content/blacksmithy/_blacksmithy.dme"
	#include "../../mods/content/blob/_blob.dme"
	#include "../../mods/content/breath_holding/_breath_holding.dme"
	#include "../../mods/content/corporate/_corporate.dme"
	#include "../../mods/content/dungeon_loot/_dungeon_loot.dme"
	#include "../../mods/content/exploration/_exploration.dme"
	#include "../../mods/content/government/_government.dme"
	#include "../../mods/content/integrated_electronics/_integrated_electronics.dme"
	#include "../../mods/content/item_sharpening/_item_sharpening.dme"
	#include "../../mods/content/matchmaking/_matchmaking.dme"
	#include "../../mods/content/modern_earth/_modern_earth.dme"
	#include "../../mods/content/mouse_highlights/_mouse_highlight.dme"
	#include "../../mods/content/pheromones/_pheromones.dme"
	#include "../../mods/content/plant_dissection/_plant_dissection.dme"
	#include "../../mods/content/psionics/_psionics.dme"
	#include "../../mods/content/standard_jobs/_standard_jobs.dme"
	#include "../../mods/content/supermatter/_supermatter.dme"
	#include "../../mods/content/tabloids/_tabloids.dme"
	#include "../../mods/content/undead/_undead.dme"
	#include "../../mods/content/ventcrawl/_ventcrawl.dme"
	#include "../../mods/content/xenobiology/_xenobiology.dme"

	#include "../../mods/gamemodes/cult/_cult.dme"
	#include "../../mods/gamemodes/heist/_heist.dme"
	#include "../../mods/gamemodes/mercenary/_mercenary.dme"
	#include "../../mods/gamemodes/ninja/_ninja.dme"
	#include "../../mods/gamemodes/revolution/_revolution.dme"
	#include "../../mods/gamemodes/traitor/_traitor.dme"
	#include "../../mods/gamemodes/spyvspy/_spyvspy.dme"
	#include "../../mods/gamemodes/mixed.dm"

	#include "../../mods/species/ascent/_ascent.dme"
	#include "../../mods/species/drakes/_drakes.dme"
	#include "../../mods/species/tajaran/_tajaran.dme"
	#include "../../mods/species/unathi/_unathi.dme"
	#include "../../mods/species/skrell/_skrell.dme"
//	#include "../../mods/species/adherent/_adherent.dme"
//	#include "../../mods/species/serpentid/_serpentid.dme"
	#include "../../mods/species/utility_frames/_utility_frames.dme"

	#include "../random_ruins/exoplanet_ruins/crashed_pod/crashed_pod.dm"

	#include "../../mods/content/government/away_sites/icarus/icarus.dm"
	#include "../../mods/content/corporate/away_sites/lar_maria/lar_maria.dm"

	#include "../away/casino/casino.dm"
	#include "../away/derelict/derelict.dm"
	#include "../away/errant_pisces/errant_pisces.dm"
	#include "../away/lost_supply_base/lost_supply_base.dm"
	#include "../away/magshield/magshield.dm"
	#include "../away/mining/mining.dm"
	#include "../away/mobius_rift/mobius_rift.dm"
	#include "../away/smugglers/smugglers.dm"
//	#include "../away/unishi/unishi.dm"
	#include "../away/yacht/yacht.dm"

	#include "areas/_areas.dm"
	#include "areas/backstage.dm"
	#include "areas/scrapyard.dm"
	#include "areas/slammer.dm"
	#include "areas/station.dm"
	#include "areas/substation.dm"

//	#include "lonestar_levels/_lonestar_submaps.dm"
	#include "lonestar_levels/_lonestar_levels.dm"
	#include "lonestar_levels/_lonestar_strata.dm"

//	#include "lonestar_levels/lonestar_levels/submaps/junkyard/_junkyard.dm"
//	#include "lonestar_levels/lonestar_levels/submaps/junkyard/_junkyard_areas.dm"

//	#include "lonestar_levels/lonestar_levels/submaps/slammer/_slammer.dm"
//	#include "lonestar_levels/lonestar_levels/submaps/slammer/_slammer_areas.dm"

//	#include "offsite/_offsite.dm"
//	#include "dungeon/_dungeon.dm"

	#include "outfits/_armors.dm"
	#include "outfits/_boots.dm"
	#include "outfits/_hats.dm"
	#include "outfits/_jobs.dm"

	#include "shuttles/_shuttles.dm"
	#include "shuttles/crew_shuttles.dm"
	#include "shuttles/homestead_bus.dm"
	#include "shuttles/hunter_shuttle.dm"
	#include "shuttles/outlaw_ship.dm"
	#include "shuttles/privateer_ship.dm"
	#include "shuttles/response_ship.dm"

	#include "lonestar_goals.dm"

	#include "lonestar_announcements.dm"
	#include "lonestar_cameras.dm"
	#include "lonestar_departments.dm"
	#include "lonestar_elevator.dm"
	#include "lonestar_exits.dm"
	#include "lonestar_spawnpoints.dm"

	#include "lonestar_loadout.dm"
	#include "lonestar_overmap.dm"
	#include "lonestar_setup.dm"

	#include "lonestar-01.dmm" //Deck 01
	#include "lonestar-02.dmm" //Deck 02
	#include "lonestar-03.dmm" //Deck 03
	#include "lonestar-04.dmm" //Vima Topside
	#include "lonestar-05.dmm" //the Slammer
	#include "lonestar-06.dmm" //the Junkyard
	#include "lonestar-07.dmm" //the Crumble
	#include "lonestar-08.dmm" //Transit Station
//	#include "lonestar-09.dmm"
//	#include "lonestar-11.dmm"

//	#include "lonestar/levels/_lonestar_levels.dm"
//	#include "lonestar/levels/_lonestar_strata.dm"
	#include "lonestar_levels/_lonestar_submaps.dm"
	//the crumble
	#include "lonestar_levels/submaps/crumble/_crumble.dm"
	#include "lonestar_levels/submaps/crumble/asteroids/asteroid.dm"
	#include "lonestar_levels/submaps/crumble/asteroids/asteroid_01.dmm"
	#include "lonestar_levels/submaps/crumble/asteroids/asteroid_02.dmm"
	#include "lonestar_levels/submaps/crumble/asteroids/asteroid_03.dmm"
	#include "lonestar_levels/submaps/crumble/asteroids/asteroid_04.dmm"
	#include "lonestar_levels/submaps/crumble/asteroids/asteroid_05.dmm"
	#include "lonestar_levels/submaps/crumble/asteroids/asteroid_06.dmm"
	#include "lonestar_levels/submaps/crumble/asteroids/asteroid_07.dmm"
	#include "lonestar_levels/submaps/crumble/asteroids/asteroid_08.dmm"
	#include "lonestar_levels/submaps/crumble/asteroids/asteroid_09.dmm"
	#include "lonestar_levels/submaps/crumble/asteroids/asteroid_10.dmm"
	#include "lonestar_levels/submaps/crumble/asteroids/asteroid_l01.dmm"
	#include "lonestar_levels/submaps/crumble/asteroids/asteroid_l02.dmm"
	#include "lonestar_levels/submaps/crumble/asteroids/asteroid_l03.dmm"
	#include "lonestar_levels/submaps/crumble/asteroids/asteroid_l04.dmm"
	#include "lonestar_levels/submaps/crumble/asteroids/asteroid_l05.dmm"
	#include "lonestar_levels/submaps/crumble/asteroids/asteroid_l06.dmm"
	#include "lonestar_levels/submaps/crumble/asteroids/asteroid_l07.dmm"
	#include "lonestar_levels/submaps/crumble/asteroids/asteroid_l08.dmm"
	#include "lonestar_levels/submaps/crumble/asteroids/asteroid_l09.dmm"
	#include "lonestar_levels/submaps/crumble/asteroids/asteroid_l10.dmm"
	#include "lonestar_levels/submaps/crumble/asteroids/asteroid_s01.dmm"
	#include "lonestar_levels/submaps/crumble/asteroids/asteroid_s02.dmm"
	#include "lonestar_levels/submaps/crumble/asteroids/asteroid_s03.dmm"
	#include "lonestar_levels/submaps/crumble/asteroids/asteroid_s04.dmm"
	#include "lonestar_levels/submaps/crumble/asteroids/asteroid_s05.dmm"
	#include "lonestar_levels/submaps/crumble/asteroids/asteroid_s06.dmm"
	#include "lonestar_levels/submaps/crumble/asteroids/asteroid_s07.dmm"
	#include "lonestar_levels/submaps/crumble/asteroids/asteroid_s08.dmm"
	#include "lonestar_levels/submaps/crumble/asteroids/asteroid_s09.dmm"
	#include "lonestar_levels/submaps/crumble/asteroids/asteroid_s10.dmm"
	#include "lonestar_levels/submaps/crumble/garbage/garbage.dm"
	#include "lonestar_levels/submaps/crumble/garbage/boxing_champ.dmm"
	#include "lonestar_levels/submaps/crumble/garbage/dumpster.dmm"
	#include "lonestar_levels/submaps/crumble/garbage/lost_wallet.dmm"
	#include "lonestar_levels/submaps/crumble/garbage/tech_junk.dmm"
	#include "lonestar_levels/submaps/crumble/garbage/trash_pile1.dmm"
	#include "lonestar_levels/submaps/crumble/garbage/trash_pile2.dmm"
	#include "lonestar_levels/submaps/crumble/garbage/trash_pile3.dmm"
	#include "lonestar_levels/submaps/crumble/garbage/undropped_supplies.dmm"
	#include "lonestar_levels/submaps/crumble/rock_base/rock_base.dm"
	#include "lonestar_levels/submaps/crumble/rock_base/rock_base1.dmm"
	#include "lonestar_levels/submaps/crumble/space_bar/space_bar.dm"
	#include "lonestar_levels/submaps/crumble/space_bar/space_bar.dmm"
	//the junkyard
	#include "lonestar_levels/submaps/junkyard/_junkyard.dm"
	#include "lonestar_levels/submaps/junkyard/garbage/garbage.dm"
	#include "lonestar_levels/submaps/junkyard/garbage/dropped_supplies.dmm"
	#include "lonestar_levels/submaps/junkyard/garbage/grease_pile1.dmm"
	#include "lonestar_levels/submaps/junkyard/garbage/grease_pile2.dmm"
	#include "lonestar_levels/submaps/junkyard/garbage/grease_pile3.dmm"
	#include "lonestar_levels/submaps/junkyard/garbage/grease_pile4.dmm"
	#include "lonestar_levels/submaps/junkyard/garbage/grease_pile5.dmm"
	#include "lonestar_levels/submaps/junkyard/geology/geology.dm"
	#include "lonestar_levels/submaps/junkyard/geology/crystal_growth.dmm"
	#include "lonestar_levels/submaps/junkyard/geology/pascal_b.dmm"
	#include "lonestar_levels/submaps/junkyard/rodeo_pit/rodeo_pit.dm"
	#include "lonestar_levels/submaps/junkyard/rodeo_pit/rodeo_pit.dmm"
	#include "lonestar_levels/submaps/junkyard/ships_ai/ships_ai.dm"
	#include "lonestar_levels/submaps/junkyard/ships_dumb/ships_dumb.dm"
	#include "lonestar_levels/submaps/junkyard/ships_dumb/containment1.dmm"
	#include "lonestar_levels/submaps/junkyard/ships_dumb/containment2.dmm"
	#include "lonestar_levels/submaps/junkyard/ships_dumb/containment3.dmm"
	#include "lonestar_levels/submaps/junkyard/ships_dumb/containment4.dmm"
	#include "lonestar_levels/submaps/junkyard/ships_dumb/containment5.dmm"
	#include "lonestar_levels/submaps/junkyard/ships_dumb/medical1.dmm"
	#include "lonestar_levels/submaps/junkyard/ships_dumb/medical2.dmm"
	#include "lonestar_levels/submaps/junkyard/ships_dumb/mercenary1.dmm"
	#include "lonestar_levels/submaps/junkyard/ships_dumb/mercenary2.dmm"
	#include "lonestar_levels/submaps/junkyard/ships_dumb/mercenary3.dmm"
	#include "lonestar_levels/submaps/junkyard/ships_dumb/quarantine.dmm"
	#include "lonestar_levels/submaps/junkyard/ships_junk/ships_junk.dm"
	#include "lonestar_levels/submaps/junkyard/ships_junk/decoupled_engine.dmm"
	#include "lonestar_levels/submaps/junkyard/ships_junk/escape_pods1.dmm"
	#include "lonestar_levels/submaps/junkyard/ships_junk/escape_pods2.dmm"
	#include "lonestar_levels/submaps/junkyard/ships_junk/escape_pods3.dmm"
	#include "lonestar_levels/submaps/junkyard/ships_junk/escape_pods4.dmm"
	//the slammer
	#include "lonestar_levels/submaps/slammer/_slammer.dm"
	#include "lonestar_levels/submaps/slammer/caves/caves.dm"
	#include "lonestar_levels/submaps/slammer/caves/bats1.dmm"
	#include "lonestar_levels/submaps/slammer/caves/bats2.dmm"
	#include "lonestar_levels/submaps/slammer/caves/bats3.dmm"
	#include "lonestar_levels/submaps/slammer/caves/bats4.dmm"
	#include "lonestar_levels/submaps/slammer/caves/bats5.dmm"
	#include "lonestar_levels/submaps/slammer/caves/bear1.dmm"
	#include "lonestar_levels/submaps/slammer/caves/cavern1.dmm"
	#include "lonestar_levels/submaps/slammer/caves/cavern2.dmm"
	#include "lonestar_levels/submaps/slammer/caves/hive2.dmm"
//	#include "lonestar_levels/submaps/slammer/caves/ice_cave1A.dmm" //no ice caves
	#include "lonestar_levels/submaps/slammer/caves/ice_junction.dmm"
	#include "lonestar_levels/submaps/slammer/caves/loose_caves.dmm"
	#include "lonestar_levels/submaps/slammer/caves/swimming_hole.dmm"
	#include "lonestar_levels/submaps/slammer/geology/geology.dm"
	#include "lonestar_levels/submaps/slammer/geology/cliff1.dmm"
	#include "lonestar_levels/submaps/slammer/geology/cliff2.dmm"
	#include "lonestar_levels/submaps/slammer/geology/crystal1.dmm"
	#include "lonestar_levels/submaps/slammer/geology/crystal2.dmm"
//	#include "lonestar_levels/submaps/slammer/ice_floe/ice_floe.dm"
//	#include "lonestar_levels/submaps/slammer/ice_floe/ice_floe.dmm."
	#include "lonestar_levels/submaps/slammer/miner_camps/miner_camps.dm"
	#include "lonestar_levels/submaps/slammer/miner_camps/miner_camp1.dmm"
	#include "lonestar_levels/submaps/slammer/stashes/stashes.dm"
	#include "lonestar_levels/submaps/slammer/stashes/buried_stash1.dmm"
	#include "lonestar_levels/submaps/slammer/stashes/buried_stash2.dmm"
	#include "lonestar_levels/submaps/slammer/stashes/buried_stash3.dmm"
	#include "lonestar_levels/submaps/slammer/stashes/hidden_stash1.dmm"
	#include "lonestar_levels/submaps/slammer/stashes/loot_stash1.dmm"
	#include "lonestar_levels/submaps/slammer/stashes/loot_stash2.dmm"
	#include "lonestar_levels/submaps/slammer/stashes/lost_prisoner.dmm"
	#include "lonestar_levels/submaps/slammer/stashes/lost_ripley.dmm"
	#include "lonestar_levels/submaps/slammer/traphouse/traphouse.dm"
	#include "lonestar_levels/submaps/slammer/traphouse/traphouse.dmm"

	#include "jobs/_jobs.dm"
	#include "jobs/_outfits.dm"
	#include "jobs/civilian.dm"
	#include "jobs/command.dm"
	#include "jobs/engineering.dm"
	#include "jobs/garage.dm"
	#include "jobs/medical.dm"
	#include "jobs/ranch.dm"
	#include "jobs/sheriff.dm"


	#define USING_MAP_DATUM /datum/map/lonestar

#elif !defined(MAP_OVERRIDE)
	#warn A map has already been included, ignoring Lonestar
#endif